#!/bin/bash
# sync-env.sh — Generate component-specific config files from root .env
# Single source of truth: root .env (ADR-009)
#
# Usage: ./scripts/sync-env.sh
# Called automatically by Xcode Build Phase before compilation.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "error: .env file not found at $ENV_FILE"
    echo "error: Copy .env.example to .env and fill in real values."
    exit 1
fi

# Read specific variables from .env
get_env_var() {
    local key="$1"
    local value
    value=$(grep "^${key}=" "$ENV_FILE" | head -1 | cut -d'=' -f2-)
    # Trim whitespace
    echo "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

SUPABASE_URL=$(get_env_var "SUPABASE_URL")
SUPABASE_ANON_KEY=$(get_env_var "SUPABASE_ANON_KEY")

# Validate required variables
if [ -z "$SUPABASE_URL" ]; then
    echo "error: SUPABASE_URL is not set in .env"
    exit 1
fi
if [ -z "$SUPABASE_ANON_KEY" ]; then
    echo "error: SUPABASE_ANON_KEY is not set in .env"
    exit 1
fi

# --- iOS: Generate Secrets.swift ---
# Using a Swift file instead of xcconfig to avoid the // comment parsing issue
# (xcconfig treats // inside URLs as line comments)
IOS_CONFIG_DIR="$ROOT_DIR/ios/Unblur/Config"
mkdir -p "$IOS_CONFIG_DIR"

cat > "$IOS_CONFIG_DIR/Secrets.swift" << EOF
// Auto-generated by sync-env.sh — DO NOT EDIT
// Source: root .env (ADR-009)

enum Secrets {
    static let supabaseURL = "${SUPABASE_URL}"
    static let supabaseAnonKey = "${SUPABASE_ANON_KEY}"
}
EOF

echo "Generated $IOS_CONFIG_DIR/Secrets.swift"

# --- Web Admin: Generate .env.local (when admin/ exists) ---
ADMIN_DIR="$ROOT_DIR/admin"
if [ -d "$ADMIN_DIR" ]; then
    cat > "$ADMIN_DIR/.env.local" << EOF
# Auto-generated by sync-env.sh — DO NOT EDIT
# Source: root .env (ADR-009)

NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
EOF
    echo "Generated $ADMIN_DIR/.env.local"
fi
